# Generated by Django 4.0 on 2022-01-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_parameters',
            new_name='login',
        ),
    ]
