# Generated by Django 4.0 on 2022-01-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_login_parameters_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_parameters',
        ),
    ]
