# Generated by Django 4.0 on 2022-01-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_login_login_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_parameters',
            name='session',
            field=models.IntegerField(),
        ),
    ]
